### ISSUE TITLE
References to generated classes do not seem to be released between iterations

### ISSUE THREAD

**Issue by elizarov** [Devexperts/lin-check#3]
If you run for a lot of iterations you end up with:

```
java.lang.OutOfMemoryError: Compressed class space

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.devexperts.dxlab.lincheck.TestThreadExecutionGenerator$ExecutionClassLoader.define(TestThreadExecutionGenerator.java:266)
	at com.devexperts.dxlab.lincheck.TestThreadExecutionGenerator$ExecutionClassLoader.access$100(TestThreadExecutionGenerator.java:264)
	at com.devexperts.dxlab.lincheck.TestThreadExecutionGenerator.create(TestThreadExecutionGenerator.java:92)
	at com.devexperts.dxlab.lincheck.LinChecker.executeActors(LinChecker.java:193)
	at com.devexperts.dxlab.lincheck.LinChecker.lambda$checkImpl$4(LinChecker.java:140)
	at com.devexperts.dxlab.lincheck.LinChecker$$Lambda$21/457233904.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.devexperts.dxlab.lincheck.LinChecker.checkImpl(LinChecker.java:150)
	at com.devexperts.dxlab.lincheck.LinChecker.lambda$check$0(LinChecker.java:69)
	at com.devexperts.dxlab.lincheck.LinChecker$$Lambda$7/977993101.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.devexperts.dxlab.lincheck.LinChecker.check(LinChecker.java:67)
	at com.devexperts.dxlab.lincheck.LinChecker.check(LinChecker.java:60)
```

**Comment by ndkoval** [comment]
Fixed in lin-check 1.8
